//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace RDMAQUINARIAS.COMPRAS.ERP_COM_REPORTES {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("DS_COM_DATOS")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class DS_COM_DATOS : global::System.Data.DataSet {
        
        private EPR_COM_ORDEN_PEDIDO_CABDataTable tableEPR_COM_ORDEN_PEDIDO_CAB;
        
        private EPR_COM_ORDEN_PEDIDO_DETDataTable tableEPR_COM_ORDEN_PEDIDO_DET;
        
        private global::System.Data.DataRelation relationEPR_COM_ORDEN_PEDIDO_CAB_EPR_COM_ORDEN_PEDIDO_DET;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public DS_COM_DATOS() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected DS_COM_DATOS(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["EPR_COM_ORDEN_PEDIDO_CAB"] != null)) {
                    base.Tables.Add(new EPR_COM_ORDEN_PEDIDO_CABDataTable(ds.Tables["EPR_COM_ORDEN_PEDIDO_CAB"]));
                }
                if ((ds.Tables["EPR_COM_ORDEN_PEDIDO_DET"] != null)) {
                    base.Tables.Add(new EPR_COM_ORDEN_PEDIDO_DETDataTable(ds.Tables["EPR_COM_ORDEN_PEDIDO_DET"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public EPR_COM_ORDEN_PEDIDO_CABDataTable EPR_COM_ORDEN_PEDIDO_CAB {
            get {
                return this.tableEPR_COM_ORDEN_PEDIDO_CAB;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public EPR_COM_ORDEN_PEDIDO_DETDataTable EPR_COM_ORDEN_PEDIDO_DET {
            get {
                return this.tableEPR_COM_ORDEN_PEDIDO_DET;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            DS_COM_DATOS cln = ((DS_COM_DATOS)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["EPR_COM_ORDEN_PEDIDO_CAB"] != null)) {
                    base.Tables.Add(new EPR_COM_ORDEN_PEDIDO_CABDataTable(ds.Tables["EPR_COM_ORDEN_PEDIDO_CAB"]));
                }
                if ((ds.Tables["EPR_COM_ORDEN_PEDIDO_DET"] != null)) {
                    base.Tables.Add(new EPR_COM_ORDEN_PEDIDO_DETDataTable(ds.Tables["EPR_COM_ORDEN_PEDIDO_DET"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableEPR_COM_ORDEN_PEDIDO_CAB = ((EPR_COM_ORDEN_PEDIDO_CABDataTable)(base.Tables["EPR_COM_ORDEN_PEDIDO_CAB"]));
            if ((initTable == true)) {
                if ((this.tableEPR_COM_ORDEN_PEDIDO_CAB != null)) {
                    this.tableEPR_COM_ORDEN_PEDIDO_CAB.InitVars();
                }
            }
            this.tableEPR_COM_ORDEN_PEDIDO_DET = ((EPR_COM_ORDEN_PEDIDO_DETDataTable)(base.Tables["EPR_COM_ORDEN_PEDIDO_DET"]));
            if ((initTable == true)) {
                if ((this.tableEPR_COM_ORDEN_PEDIDO_DET != null)) {
                    this.tableEPR_COM_ORDEN_PEDIDO_DET.InitVars();
                }
            }
            this.relationEPR_COM_ORDEN_PEDIDO_CAB_EPR_COM_ORDEN_PEDIDO_DET = this.Relations["EPR_COM_ORDEN_PEDIDO_CAB_EPR_COM_ORDEN_PEDIDO_DET"];
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private void InitClass() {
            this.DataSetName = "DS_COM_DATOS";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DS_COM_DATOS.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableEPR_COM_ORDEN_PEDIDO_CAB = new EPR_COM_ORDEN_PEDIDO_CABDataTable();
            base.Tables.Add(this.tableEPR_COM_ORDEN_PEDIDO_CAB);
            this.tableEPR_COM_ORDEN_PEDIDO_DET = new EPR_COM_ORDEN_PEDIDO_DETDataTable();
            base.Tables.Add(this.tableEPR_COM_ORDEN_PEDIDO_DET);
            this.relationEPR_COM_ORDEN_PEDIDO_CAB_EPR_COM_ORDEN_PEDIDO_DET = new global::System.Data.DataRelation("EPR_COM_ORDEN_PEDIDO_CAB_EPR_COM_ORDEN_PEDIDO_DET", new global::System.Data.DataColumn[] {
                        this.tableEPR_COM_ORDEN_PEDIDO_CAB.nuPedColumn}, new global::System.Data.DataColumn[] {
                        this.tableEPR_COM_ORDEN_PEDIDO_DET.nuPedColumn}, false);
            this.Relations.Add(this.relationEPR_COM_ORDEN_PEDIDO_CAB_EPR_COM_ORDEN_PEDIDO_DET);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private bool ShouldSerializeEPR_COM_ORDEN_PEDIDO_CAB() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private bool ShouldSerializeEPR_COM_ORDEN_PEDIDO_DET() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            DS_COM_DATOS ds = new DS_COM_DATOS();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public delegate void EPR_COM_ORDEN_PEDIDO_CABRowChangeEventHandler(object sender, EPR_COM_ORDEN_PEDIDO_CABRowChangeEvent e);
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public delegate void EPR_COM_ORDEN_PEDIDO_DETRowChangeEventHandler(object sender, EPR_COM_ORDEN_PEDIDO_DETRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class EPR_COM_ORDEN_PEDIDO_CABDataTable : global::System.Data.TypedTableBase<EPR_COM_ORDEN_PEDIDO_CABRow> {
            
            private global::System.Data.DataColumn columnnuPed;
            
            private global::System.Data.DataColumn columncoProvCli;
            
            private global::System.Data.DataColumn columndeProvCli;
            
            private global::System.Data.DataColumn columntituloPed;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public EPR_COM_ORDEN_PEDIDO_CABDataTable() {
                this.TableName = "EPR_COM_ORDEN_PEDIDO_CAB";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal EPR_COM_ORDEN_PEDIDO_CABDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected EPR_COM_ORDEN_PEDIDO_CABDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn nuPedColumn {
                get {
                    return this.columnnuPed;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn coProvCliColumn {
                get {
                    return this.columncoProvCli;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn deProvCliColumn {
                get {
                    return this.columndeProvCli;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn tituloPedColumn {
                get {
                    return this.columntituloPed;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public EPR_COM_ORDEN_PEDIDO_CABRow this[int index] {
                get {
                    return ((EPR_COM_ORDEN_PEDIDO_CABRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event EPR_COM_ORDEN_PEDIDO_CABRowChangeEventHandler EPR_COM_ORDEN_PEDIDO_CABRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event EPR_COM_ORDEN_PEDIDO_CABRowChangeEventHandler EPR_COM_ORDEN_PEDIDO_CABRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event EPR_COM_ORDEN_PEDIDO_CABRowChangeEventHandler EPR_COM_ORDEN_PEDIDO_CABRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event EPR_COM_ORDEN_PEDIDO_CABRowChangeEventHandler EPR_COM_ORDEN_PEDIDO_CABRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void AddEPR_COM_ORDEN_PEDIDO_CABRow(EPR_COM_ORDEN_PEDIDO_CABRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public EPR_COM_ORDEN_PEDIDO_CABRow AddEPR_COM_ORDEN_PEDIDO_CABRow(string nuPed, string coProvCli, string deProvCli, string tituloPed) {
                EPR_COM_ORDEN_PEDIDO_CABRow rowEPR_COM_ORDEN_PEDIDO_CABRow = ((EPR_COM_ORDEN_PEDIDO_CABRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        nuPed,
                        coProvCli,
                        deProvCli,
                        tituloPed};
                rowEPR_COM_ORDEN_PEDIDO_CABRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowEPR_COM_ORDEN_PEDIDO_CABRow);
                return rowEPR_COM_ORDEN_PEDIDO_CABRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                EPR_COM_ORDEN_PEDIDO_CABDataTable cln = ((EPR_COM_ORDEN_PEDIDO_CABDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new EPR_COM_ORDEN_PEDIDO_CABDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal void InitVars() {
                this.columnnuPed = base.Columns["nuPed"];
                this.columncoProvCli = base.Columns["coProvCli"];
                this.columndeProvCli = base.Columns["deProvCli"];
                this.columntituloPed = base.Columns["tituloPed"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            private void InitClass() {
                this.columnnuPed = new global::System.Data.DataColumn("nuPed", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnuPed);
                this.columncoProvCli = new global::System.Data.DataColumn("coProvCli", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncoProvCli);
                this.columndeProvCli = new global::System.Data.DataColumn("deProvCli", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columndeProvCli);
                this.columntituloPed = new global::System.Data.DataColumn("tituloPed", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntituloPed);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public EPR_COM_ORDEN_PEDIDO_CABRow NewEPR_COM_ORDEN_PEDIDO_CABRow() {
                return ((EPR_COM_ORDEN_PEDIDO_CABRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new EPR_COM_ORDEN_PEDIDO_CABRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(EPR_COM_ORDEN_PEDIDO_CABRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.EPR_COM_ORDEN_PEDIDO_CABRowChanged != null)) {
                    this.EPR_COM_ORDEN_PEDIDO_CABRowChanged(this, new EPR_COM_ORDEN_PEDIDO_CABRowChangeEvent(((EPR_COM_ORDEN_PEDIDO_CABRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.EPR_COM_ORDEN_PEDIDO_CABRowChanging != null)) {
                    this.EPR_COM_ORDEN_PEDIDO_CABRowChanging(this, new EPR_COM_ORDEN_PEDIDO_CABRowChangeEvent(((EPR_COM_ORDEN_PEDIDO_CABRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.EPR_COM_ORDEN_PEDIDO_CABRowDeleted != null)) {
                    this.EPR_COM_ORDEN_PEDIDO_CABRowDeleted(this, new EPR_COM_ORDEN_PEDIDO_CABRowChangeEvent(((EPR_COM_ORDEN_PEDIDO_CABRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.EPR_COM_ORDEN_PEDIDO_CABRowDeleting != null)) {
                    this.EPR_COM_ORDEN_PEDIDO_CABRowDeleting(this, new EPR_COM_ORDEN_PEDIDO_CABRowChangeEvent(((EPR_COM_ORDEN_PEDIDO_CABRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void RemoveEPR_COM_ORDEN_PEDIDO_CABRow(EPR_COM_ORDEN_PEDIDO_CABRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                DS_COM_DATOS ds = new DS_COM_DATOS();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "EPR_COM_ORDEN_PEDIDO_CABDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class EPR_COM_ORDEN_PEDIDO_DETDataTable : global::System.Data.TypedTableBase<EPR_COM_ORDEN_PEDIDO_DETRow> {
            
            private global::System.Data.DataColumn columnnuPed;
            
            private global::System.Data.DataColumn columnitem;
            
            private global::System.Data.DataColumn columncoProd;
            
            private global::System.Data.DataColumn columndeProd;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public EPR_COM_ORDEN_PEDIDO_DETDataTable() {
                this.TableName = "EPR_COM_ORDEN_PEDIDO_DET";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal EPR_COM_ORDEN_PEDIDO_DETDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected EPR_COM_ORDEN_PEDIDO_DETDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn nuPedColumn {
                get {
                    return this.columnnuPed;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn itemColumn {
                get {
                    return this.columnitem;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn coProdColumn {
                get {
                    return this.columncoProd;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn deProdColumn {
                get {
                    return this.columndeProd;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public EPR_COM_ORDEN_PEDIDO_DETRow this[int index] {
                get {
                    return ((EPR_COM_ORDEN_PEDIDO_DETRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event EPR_COM_ORDEN_PEDIDO_DETRowChangeEventHandler EPR_COM_ORDEN_PEDIDO_DETRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event EPR_COM_ORDEN_PEDIDO_DETRowChangeEventHandler EPR_COM_ORDEN_PEDIDO_DETRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event EPR_COM_ORDEN_PEDIDO_DETRowChangeEventHandler EPR_COM_ORDEN_PEDIDO_DETRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event EPR_COM_ORDEN_PEDIDO_DETRowChangeEventHandler EPR_COM_ORDEN_PEDIDO_DETRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void AddEPR_COM_ORDEN_PEDIDO_DETRow(EPR_COM_ORDEN_PEDIDO_DETRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public EPR_COM_ORDEN_PEDIDO_DETRow AddEPR_COM_ORDEN_PEDIDO_DETRow(EPR_COM_ORDEN_PEDIDO_CABRow parentEPR_COM_ORDEN_PEDIDO_CABRowByEPR_COM_ORDEN_PEDIDO_CAB_EPR_COM_ORDEN_PEDIDO_DET, string item, string coProd, string deProd) {
                EPR_COM_ORDEN_PEDIDO_DETRow rowEPR_COM_ORDEN_PEDIDO_DETRow = ((EPR_COM_ORDEN_PEDIDO_DETRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        null,
                        item,
                        coProd,
                        deProd};
                if ((parentEPR_COM_ORDEN_PEDIDO_CABRowByEPR_COM_ORDEN_PEDIDO_CAB_EPR_COM_ORDEN_PEDIDO_DET != null)) {
                    columnValuesArray[0] = parentEPR_COM_ORDEN_PEDIDO_CABRowByEPR_COM_ORDEN_PEDIDO_CAB_EPR_COM_ORDEN_PEDIDO_DET[0];
                }
                rowEPR_COM_ORDEN_PEDIDO_DETRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowEPR_COM_ORDEN_PEDIDO_DETRow);
                return rowEPR_COM_ORDEN_PEDIDO_DETRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                EPR_COM_ORDEN_PEDIDO_DETDataTable cln = ((EPR_COM_ORDEN_PEDIDO_DETDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new EPR_COM_ORDEN_PEDIDO_DETDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal void InitVars() {
                this.columnnuPed = base.Columns["nuPed"];
                this.columnitem = base.Columns["item"];
                this.columncoProd = base.Columns["coProd"];
                this.columndeProd = base.Columns["deProd"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            private void InitClass() {
                this.columnnuPed = new global::System.Data.DataColumn("nuPed", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnuPed);
                this.columnitem = new global::System.Data.DataColumn("item", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnitem);
                this.columncoProd = new global::System.Data.DataColumn("coProd", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncoProd);
                this.columndeProd = new global::System.Data.DataColumn("deProd", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columndeProd);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public EPR_COM_ORDEN_PEDIDO_DETRow NewEPR_COM_ORDEN_PEDIDO_DETRow() {
                return ((EPR_COM_ORDEN_PEDIDO_DETRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new EPR_COM_ORDEN_PEDIDO_DETRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(EPR_COM_ORDEN_PEDIDO_DETRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.EPR_COM_ORDEN_PEDIDO_DETRowChanged != null)) {
                    this.EPR_COM_ORDEN_PEDIDO_DETRowChanged(this, new EPR_COM_ORDEN_PEDIDO_DETRowChangeEvent(((EPR_COM_ORDEN_PEDIDO_DETRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.EPR_COM_ORDEN_PEDIDO_DETRowChanging != null)) {
                    this.EPR_COM_ORDEN_PEDIDO_DETRowChanging(this, new EPR_COM_ORDEN_PEDIDO_DETRowChangeEvent(((EPR_COM_ORDEN_PEDIDO_DETRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.EPR_COM_ORDEN_PEDIDO_DETRowDeleted != null)) {
                    this.EPR_COM_ORDEN_PEDIDO_DETRowDeleted(this, new EPR_COM_ORDEN_PEDIDO_DETRowChangeEvent(((EPR_COM_ORDEN_PEDIDO_DETRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.EPR_COM_ORDEN_PEDIDO_DETRowDeleting != null)) {
                    this.EPR_COM_ORDEN_PEDIDO_DETRowDeleting(this, new EPR_COM_ORDEN_PEDIDO_DETRowChangeEvent(((EPR_COM_ORDEN_PEDIDO_DETRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void RemoveEPR_COM_ORDEN_PEDIDO_DETRow(EPR_COM_ORDEN_PEDIDO_DETRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                DS_COM_DATOS ds = new DS_COM_DATOS();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "EPR_COM_ORDEN_PEDIDO_DETDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class EPR_COM_ORDEN_PEDIDO_CABRow : global::System.Data.DataRow {
            
            private EPR_COM_ORDEN_PEDIDO_CABDataTable tableEPR_COM_ORDEN_PEDIDO_CAB;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal EPR_COM_ORDEN_PEDIDO_CABRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableEPR_COM_ORDEN_PEDIDO_CAB = ((EPR_COM_ORDEN_PEDIDO_CABDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string nuPed {
                get {
                    try {
                        return ((string)(this[this.tableEPR_COM_ORDEN_PEDIDO_CAB.nuPedColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'nuPed\' de la tabla \'EPR_COM_ORDEN_PEDIDO_CAB\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEPR_COM_ORDEN_PEDIDO_CAB.nuPedColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string coProvCli {
                get {
                    try {
                        return ((string)(this[this.tableEPR_COM_ORDEN_PEDIDO_CAB.coProvCliColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'coProvCli\' de la tabla \'EPR_COM_ORDEN_PEDIDO_CAB\' es DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableEPR_COM_ORDEN_PEDIDO_CAB.coProvCliColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string deProvCli {
                get {
                    try {
                        return ((string)(this[this.tableEPR_COM_ORDEN_PEDIDO_CAB.deProvCliColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'deProvCli\' de la tabla \'EPR_COM_ORDEN_PEDIDO_CAB\' es DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableEPR_COM_ORDEN_PEDIDO_CAB.deProvCliColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string tituloPed {
                get {
                    try {
                        return ((string)(this[this.tableEPR_COM_ORDEN_PEDIDO_CAB.tituloPedColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'tituloPed\' de la tabla \'EPR_COM_ORDEN_PEDIDO_CAB\' es DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableEPR_COM_ORDEN_PEDIDO_CAB.tituloPedColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsnuPedNull() {
                return this.IsNull(this.tableEPR_COM_ORDEN_PEDIDO_CAB.nuPedColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetnuPedNull() {
                this[this.tableEPR_COM_ORDEN_PEDIDO_CAB.nuPedColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IscoProvCliNull() {
                return this.IsNull(this.tableEPR_COM_ORDEN_PEDIDO_CAB.coProvCliColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetcoProvCliNull() {
                this[this.tableEPR_COM_ORDEN_PEDIDO_CAB.coProvCliColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsdeProvCliNull() {
                return this.IsNull(this.tableEPR_COM_ORDEN_PEDIDO_CAB.deProvCliColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetdeProvCliNull() {
                this[this.tableEPR_COM_ORDEN_PEDIDO_CAB.deProvCliColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IstituloPedNull() {
                return this.IsNull(this.tableEPR_COM_ORDEN_PEDIDO_CAB.tituloPedColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SettituloPedNull() {
                this[this.tableEPR_COM_ORDEN_PEDIDO_CAB.tituloPedColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public EPR_COM_ORDEN_PEDIDO_DETRow[] GetEPR_COM_ORDEN_PEDIDO_DETRows() {
                if ((this.Table.ChildRelations["EPR_COM_ORDEN_PEDIDO_CAB_EPR_COM_ORDEN_PEDIDO_DET"] == null)) {
                    return new EPR_COM_ORDEN_PEDIDO_DETRow[0];
                }
                else {
                    return ((EPR_COM_ORDEN_PEDIDO_DETRow[])(base.GetChildRows(this.Table.ChildRelations["EPR_COM_ORDEN_PEDIDO_CAB_EPR_COM_ORDEN_PEDIDO_DET"])));
                }
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class EPR_COM_ORDEN_PEDIDO_DETRow : global::System.Data.DataRow {
            
            private EPR_COM_ORDEN_PEDIDO_DETDataTable tableEPR_COM_ORDEN_PEDIDO_DET;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal EPR_COM_ORDEN_PEDIDO_DETRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableEPR_COM_ORDEN_PEDIDO_DET = ((EPR_COM_ORDEN_PEDIDO_DETDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string nuPed {
                get {
                    try {
                        return ((string)(this[this.tableEPR_COM_ORDEN_PEDIDO_DET.nuPedColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'nuPed\' de la tabla \'EPR_COM_ORDEN_PEDIDO_DET\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEPR_COM_ORDEN_PEDIDO_DET.nuPedColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string item {
                get {
                    try {
                        return ((string)(this[this.tableEPR_COM_ORDEN_PEDIDO_DET.itemColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'item\' de la tabla \'EPR_COM_ORDEN_PEDIDO_DET\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableEPR_COM_ORDEN_PEDIDO_DET.itemColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string coProd {
                get {
                    try {
                        return ((string)(this[this.tableEPR_COM_ORDEN_PEDIDO_DET.coProdColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'coProd\' de la tabla \'EPR_COM_ORDEN_PEDIDO_DET\' es DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableEPR_COM_ORDEN_PEDIDO_DET.coProdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string deProd {
                get {
                    try {
                        return ((string)(this[this.tableEPR_COM_ORDEN_PEDIDO_DET.deProdColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'deProd\' de la tabla \'EPR_COM_ORDEN_PEDIDO_DET\' es DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableEPR_COM_ORDEN_PEDIDO_DET.deProdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public EPR_COM_ORDEN_PEDIDO_CABRow EPR_COM_ORDEN_PEDIDO_CABRow {
                get {
                    return ((EPR_COM_ORDEN_PEDIDO_CABRow)(this.GetParentRow(this.Table.ParentRelations["EPR_COM_ORDEN_PEDIDO_CAB_EPR_COM_ORDEN_PEDIDO_DET"])));
                }
                set {
                    this.SetParentRow(value, this.Table.ParentRelations["EPR_COM_ORDEN_PEDIDO_CAB_EPR_COM_ORDEN_PEDIDO_DET"]);
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsnuPedNull() {
                return this.IsNull(this.tableEPR_COM_ORDEN_PEDIDO_DET.nuPedColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetnuPedNull() {
                this[this.tableEPR_COM_ORDEN_PEDIDO_DET.nuPedColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsitemNull() {
                return this.IsNull(this.tableEPR_COM_ORDEN_PEDIDO_DET.itemColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetitemNull() {
                this[this.tableEPR_COM_ORDEN_PEDIDO_DET.itemColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IscoProdNull() {
                return this.IsNull(this.tableEPR_COM_ORDEN_PEDIDO_DET.coProdColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetcoProdNull() {
                this[this.tableEPR_COM_ORDEN_PEDIDO_DET.coProdColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsdeProdNull() {
                return this.IsNull(this.tableEPR_COM_ORDEN_PEDIDO_DET.deProdColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetdeProdNull() {
                this[this.tableEPR_COM_ORDEN_PEDIDO_DET.deProdColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public class EPR_COM_ORDEN_PEDIDO_CABRowChangeEvent : global::System.EventArgs {
            
            private EPR_COM_ORDEN_PEDIDO_CABRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public EPR_COM_ORDEN_PEDIDO_CABRowChangeEvent(EPR_COM_ORDEN_PEDIDO_CABRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public EPR_COM_ORDEN_PEDIDO_CABRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public class EPR_COM_ORDEN_PEDIDO_DETRowChangeEvent : global::System.EventArgs {
            
            private EPR_COM_ORDEN_PEDIDO_DETRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public EPR_COM_ORDEN_PEDIDO_DETRowChangeEvent(EPR_COM_ORDEN_PEDIDO_DETRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public EPR_COM_ORDEN_PEDIDO_DETRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591